In [7]:
my_2d=[[1,2,3],[4,5,6],[7,8,9]]


In [1]:
import numpy as np


In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
array_5=[0,0,0,0,0]
np.array(array_5)

array([0, 0, 0, 0, 0])

In [13]:
array_10 = np.arange(0,10,1)
array_10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
boo_arr = boo>10
boo_arr

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True])

In [77]:
import numpy as np
boo = np.arange(2,14)
boo

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [87]:
boo[boo>10]

array([11, 12, 13])

In [7]:
np.arange(55,100)


array([55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88,
       89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:

my_array = np.array(my_2d)
my_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
element = my_array[1,2]
element

6

In [37]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [43]:
slice_arry= arr_2d[1:,1:]
slice_arry


array([[25, 30],
       [40, 45]])

In [9]:
np.linspace(1,95,20)


array([ 1.        ,  5.94736842, 10.89473684, 15.84210526, 20.78947368,
       25.73684211, 30.68421053, 35.63157895, 40.57894737, 45.52631579,
       50.47368421, 55.42105263, 60.36842105, 65.31578947, 70.26315789,
       75.21052632, 80.15789474, 85.10526316, 90.05263158, 95.        ])

In [11]:
np.random.rand(4)

array([0.80714159, 0.373786  , 0.57774657, 0.08938133])

In [13]:
np.random.randn(10)

array([-1.15432594,  0.49877626, -0.52240207,  1.40399116,  1.98540097,
       -0.31208164,  1.81746514, -0.59717018, -0.52174088,  1.50596516])

In [47]:
ar1=np.random.randint(10,56,12)
ar1

array([53, 15, 21, 37, 28, 22, 39, 37, 41, 16, 21, 35])

In [49]:
res=ar1.reshape(4,3)
res

array([[53, 15, 21],
       [37, 28, 22],
       [39, 37, 41],
       [16, 21, 35]])

In [51]:

res.max()



53

In [53]:
res.min()

15

In [55]:
res.argmin()

1

In [68]:
ar1<37


array([False,  True,  True, False,  True,  True, False, False, False,
        True,  True,  True])